platform: Any CPU

configuration: Release

install:
  - set QTDIR=C:\Qt\5.9.2\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\5.9.2\bin

build_script:
  - qmake CONFIG+=ui_gfx CONFIG+=release .
  - mingw32-make
