version: 0.1.{build}
platform: Any CPU

configuration: Release

install:
  - set QTDIR=C:\Qt\5.11.0\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake CONFIG+=ui_gfx CONFIG+=release .
  - mingw32-make

after_build:
  - mkdir deploy
  - copy build\mybelka.exe deploy\
  - windeployqt deploy\mybelka.exe
  - 7z a MyBelka.zip deploy

artifacts:
  - path: MyBelka.zip

deploy:
  release: MyBelka-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: BkwtaMaFu6dfSG959vhogy4AxAdnN3kzhe0TThmiVdI0rx6NH207kY4HgOMb6E27
  artifact: MyBelka.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
