sudo: required
dist: trusty
language: c++

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_script:
  - export CC=gcc-7 
  - export CXX=g++-7
  - source /opt/qt55/bin/qt55-env.sh
  - mkdir -p build
  - cd build
  - /opt/qt55/bin/qmake ..

script:
  - make 
