sudo: required
dist: trusty
language: c++

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

before_ script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - source /opt/qt55/bin/qt55-env.sh
  - mkdir -p build
  - cd build
  - /opt/qt55/bin/qmake ..

script:
  - make 
