sudo: required
dist: trusty
language: c++

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt58/bin/qt59-env.sh
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_script:
  - export CC=gcc-6
  - export CXX=g++-6
  - mkdir -p build
  - cd build
  - /opt/qt59/bin/qmake ..

script:
  - make 
